import type { Metadata } from "next";

import "@/app/ui/globals.css";
import StyledComponentsRegistry from "@/app/lib/registry";
import { inter } from "@/app/ui/fonts";
import { Navbar, Footer } from "./ui/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Navbar />
          {children}
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
